POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "jim",
    "password": "jim"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "henry",
    "password": "henry"
}


### Create all post
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYwMWU4YmYyNDVkYTU1Y2QwNzk3ZjUiLCJpYXQiOjE2NTA0NjY0NDN9.VezVbXPkIlI_TZSKjpsF2Qtk7IsOZAErB5YVTDraiw0

{
    "title": "React",
    "description": "React",
    "url": "react.com"
}

### Get all post
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYwMTcxYzQ0ZjZhMmM2M2Q2NzNmZWMiLCJpYXQiOjE2NTA0NjY3NDd9.HNs6wZsPuyYfy0YzLJh9pR1r7S9dz84Oy5dQ0wjX4js

### Modify
PUT http://localhost:5000/api/posts/62601c06c9a1ebfb0ed6596e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYwMTcxYzQ0ZjZhMmM2M2Q2NzNmZWMiLCJpYXQiOjE2NTA0NjY3NDd9.HNs6wZsPuyYfy0YzLJh9pR1r7S9dz84Oy5dQ0wjX4js

{
    "title":"Vue",
    "description": "VUEEEEE",
    "url": "vuejs.org",
    "status": "Learning"

}

###Delete
DELETE http://localhost:5000/api/posts/62601e5d8d5da2cd255f10b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYwMTcxYzQ0ZjZhMmM2M2Q2NzNmZWMiLCJpYXQiOjE2NTA0NjY3NDd9.HNs6wZsPuyYfy0YzLJh9pR1r7S9dz84Oy5dQ0wjX4js
//Code tham khao o tren
//-----------------------------------------
### Register Jobseeker// User co mat khau auto: 12345
POST http://localhost:5000/api/auth/jobseeker/register
Content-Type: application/json

{
    "email": "thebest11447@gmail.com",
    "phonenumber": "0337445596",
    "password": "12345",
    "address": "18 duong binh thung",
    "name": "Hoang Van Binh",
    "birthday": "2011-12-07"
}
### Register Emp // Emp co mat khau auto la: 123456789 (Admin too)
POST http://localhost:5000/api/auth/employer/register
Content-Type: application/json

{
    "email": "thebest11445@gmail.com",
    "phonenumber": "0979918915",
    "password": "123456789",
    "address": "Số 1 võ văn ngân thành phố Hồ chí minh",
    "companyname": "Cong Ty TNHH MTV BHQ",
    "description": "Chuyên chạy deadline"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "mode" : 0,
    "email": "thebest11447@gmail.com",
    "password": "12345"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "mode" : 2,
    "email": "19110170@student.hcmute.edu.vn",
    "password": "123456789"
}

### Get category
GET  http://localhost:5000/api/category

### delete 626ab2621919bf702d5e8054
DELETE   http://localhost:5000/api/category/626ab2621919bf702d5e8054
### PUT 626ab2621919bf702d5e8054
PUT   http://localhost:5000/api/category/626ab91973e2db7d871b216f
Content-Type: application/json

{
    "name": "aaacascas@gmail.com",
    "description": "123456789"
}

### Get info Emp

GET  http://localhost:5000/api/info/employer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTA5NjA2ODV9.m86f89FosJhDQg03NqqHKvE1j06ZedFhtC324MmlFFs


###Get info  JobSeeker

GET  http://localhost:5000/api/info/jobseeker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTA5NjE2ODN9.azUG6vqAZb2p-e1Bd46WM7oqVm2riLU3-IppvRlFf4k

### Get info Admin

GET  http://localhost:5000/api/info/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNThkMzI2MjAwNzc1NGEyY2UyYTgiLCJpYXQiOjE2NTA5NjE4ODJ9.FSjU25yViAzfVXceyHNdN478hJmusBieW0h_tltNn-Y


### Adjust info JobSeeker

PUT  http://localhost:5000/api/info/jobseeker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTA5NjI5NzB9.JqH6ks8w9ZbIInIfo2h82ISKY1vFIj0nqrJTwdImCvg
Content-Type: application/json

{
    "email": "thebest11447@gmail.com",
    "phonenumber": "0337445596",
    "address": "18 duong binh thung",
    "name": "Hoang Van Bình",
    "birthday": "2001-12-07"
}


### Adjust info JobSeeker

PUT  http://localhost:5000/api/info/employer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTA5NjM0MzF9.lr4Ogtwjbbhdk058Th92zvXUgY8EyOD7W2wIErcKFdI
Content-Type: application/json

{
    "email": "thebest11446@gmail.com",
    "phonenumber": "0918535413",
    "address": "Số 1 võ văn ngân thành phố Hồ chí minh",
    "companyname": "Trường Đại Học SPKT TP Hồ Chí Minh",
    "description": "Đào tạo tất cả các ngành Kỹ thuật"
}

###
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTE1NjQ1NzR9.zJYkBHi1R3dD2N38CAAxOCNoFY9E9gWXoGU1nQGds1o
###
PUT  http://localhost:5000/api/info/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTE1NjQ1NzR9.zJYkBHi1R3dD2N38CAAxOCNoFY9E9gWXoGU1nQGds1o
Content-Type: application/json

{
    "oldpassword": "123456789",
    "newpassword": "12345678",
    "confirmnewpassword": "12345678",
    "role": 1
}
### view
GET http://localhost:5000/api/post/admin/rejected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNThkMzI2MjAwNzc1NGEyY2UyYTgiLCJpYXQiOjE2NTI3NjM5Nzh9.kU_sAgokgy99f5VbG9ii4DZzSUqu4Lmjtg_wCg7B0To

### Delete
DELETE  http://localhost:5000/api/post/32423423432432
###
POST  http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTI3NzE1MzR9.adgE1obrKKrXusi7iE22npmQQno4FdPxEFLy4d-XqW0
Content-Type: application/json

{
            "category": "626129e3ba08c523d264991a",
            "title": "Giao hàng nhanh FFood",
            "description":"Giao hàng cấp tốc cho công ty, các loại hàng hóa đa dạng.",
            "requirement": "Có giấy phép lái xe A1",
            "salary": 8000000,
            "location": "Công ty TNHH MTV FFood, Dĩ An, Bình Dương",
            "dateEnd":"2022-12-07T00:00:00.000+00:00"
}

###

PUT http://localhost:5000/api/post/6280c5717345790749d46169
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTE2Mjk5MjJ9.Oyprym-UOZvdF2pO1KZO2yIeeD_fSHlcj_ytHczOTEg
Content-Type: application/json

{
            "category": "626129e3ba08c523d264991a",
            "title": "Cưỡi ngựa",
            "description":"Cưỡi ngựa trên các quốc lộ",
            "requirement": "Trình độ Đại Học",
            "salary": 9000000,
            "location": "Số 18 đường bình thung",
            "dateEnd":"2022-12-07T00:00:00.000+00:00"
}

###Submitted
PUT http://localhost:5000/api/submitted/6271e3b829174de1542b12b6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U


### Get Submitted
GET http://localhost:5000/api/submitted/6271e3b829174de1542b12b6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U




### Get All Profile submitted in Post
GET http://localhost:5000/api/submitted/post/62824e5f0bbc5e4cc7c4e18d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U




### Get Post Details
GET http://localhost:5000/api/postDetail/6280c5717345790749d46169
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTIzMzgzOTd9.2m9lGBfAkEAXubR9PvLESH4TwjDQHToh2x0T2SSaP0Q


### get Emp Post
GET http://localhost:5000/api/post/EmpPost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTI2MDk3NjV9.TTMUl1d9RKrbWjrBqElskfaow7rXqZiC6ZPBLYZAjQQ


### Approve // Reject
PUT http://localhost:5000/api/post/approve/6280d4a8e67522e6298c990d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNThkMzI2MjAwNzc1NGEyY2UyYTgiLCJpYXQiOjE2NTI3Njg0OTh9.AII-D7sdB3R0g7Vxr9ovdhkCCOz2OJf97Ato2p0rDQo

### Mark Post
POST http://localhost:5000/api/markPost/6280d4a8e67522e6298c990d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTI2MDk3NjV9.TTMUl1d9RKrbWjrBqElskfaow7rXqZiC6ZPBLYZAjQQ
### Mark Post
GET http://localhost:5000/api/markPost/6280d4a8e67522e6298c990d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxNTc5ODM4YjhmOWIwMzg3YjI4MDgiLCJpYXQiOjE2NTI2MDk3NjV9.TTMUl1d9RKrbWjrBqElskfaow7rXqZiC6ZPBLYZAjQQ

###
GET http://localhost:5000/api/markPost/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTI3ODExMjJ9.VurtL1jM_HvowGiKISvf09q1OR54cKhgME2wNIPLLvM

###
POST http://localhost:5000/api/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U
Content-Type: application/json

{
            "owner_email": "thebest11447@gmail.com",
            "phonenumber": "0337445596",
            "name":"Hoàng Văn Bình",
            "birthday": "2001-12-07T00:00:00.000+00:00",
            "introduce": "Sinh Vien Dai Hoc Su Pham ky Thuat TP HCM",
            "experience": "Intern",
            "degree":"Toeic 790"
}


###
GET http://localhost:5000/api/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U


###
PUT http://localhost:5000/api/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U
Content-Type: application/json

{
            "owner_email": "thebest11447@gmail.com",
            "phonenumber": "0337445596",
            "name":"Hoàng Văn Bình",
            "birthday": "2001-12-07T00:00:00.000+00:00",
            "introduce": "Sinh Vien Dai Hoc Su Pham ky Thuat TP HCM",
            "experience": "Intern",
            "degree":"Toeic 790"
}


###
POST http://localhost:5000/api/post/search 
Content-Type: application/json

{
    "cate":"626129e3ba08c523d264991a",
    "title":"",
    "location":""
}

###

###
GET http://localhost:5000/api/profile/search 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMmVhNDg3NTgwNzljMzhjNGFjZjEiLCJpYXQiOjE2NTM1NDg0Mzh9.1vU5S117r_LHuaKP6lQuDzU6i5kVun9MBbknPzNnP9U
Content-Type: application/json

{
    "search": "thebest1144"
}
